language: go
os:
  - linux
  - osx
go: 
  - 1.7
  - 1.8

install: true

script:
  - cd $GOPATH/src/github.com/amitsaha/gitbackup/
  - GOPATH=$GOPATH/src/github.com/amitsaha/gitbackup/vendor go build -o bin/gitbackup src/gitbackup/main.go src/gitbackup/client.go src/gitbackup/backup.go src/gitbackup/repositories.go
  - cd src/gitbackup/
  - GOPATH=$GOPATH/src/github.com/amitsaha/gitbackup/vendor go test -v
