language: go
os:
  - linux
  - osx
go: 
  - 1.7
  - 1.8

script:
  - go build -o bin/gitbackup src/gitbackup/main.go src/gitbackup/client.go src/gitbackup/backup.go src/gitbackup/repositories.go
  - cd src/gitbackup/
  - go test -v
