language: go
os:
  - linux
  - osx
go: 
  - 1.12.x

install: true

script:
  - cd $GOPATH/src/github.com/amitsaha/gitbackup/
  - env GO111MODULE=on go build
  - env GO111MODULE=on golint
  - env GO111MODULE=on go test -v
  - bash ./build-binaries.bash

deploy:
  provider: releases
  api_key:
    secure: $GITBACKUP_RELEASE
  file_glob: true
  file: artifacts/*.zip
  skip_cleanup: true
  on:
    tags: true
